# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 100
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 100
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 100
      runas: root
