# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

hooks:

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root
