name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./project-fetcher.sh
         ./project-fetcher.sh
      shell: bash
    - name: Get version
      id: vars
      run: echo ::set-output name=version::$(./project-fetcher.sh)
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
    - name: Test URL
      run: echo google.com/${{ steps.vars.outputs.version }}
